### PR TITLE
Using horizontal & vertical layouts for ZoneGraph

### PR DESCRIPTION
**Pull request by tadam50**
**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**
No

**What kind of change does this PR introduce?**
Feature

**What is the current behavior?**
No layouts for Zone graph are available 

**What is the new behavior (if this is a feature change)?**
Provide horizontal and vertical layouts for Zone graph

**Does this PR introduce a breaking change or deprecate an API?**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

### CODE REVIEW

**Comment by flieks** [comment]
This is great, thanks!

Just have 1 question. I see there is a horizontal example and vertical example. But can vertical and horizontal layouts be combined in 1 svg ?

For example we have 12 substations, then ideally we want to have 3 rows with each 4 substations...

**Review by So-Fras — CHANGES_REQUESTED** [review]
Thank you for your nice work!
I didn't have time to finish my review, to be continued :)

**Review by So-Fras — CHANGES_REQUESTED** [review]
Thank you for the huge amount of work you have put in this PR.
I made a minor comment, I would like to discuss it further with you because I do not get why there is a difference between substation and zone regarding layout naming (and furthermore I may be to blame here!).

**Review by So-Fras — APPROVED** [review]

**Comment by So-Fras** [comment]
Some configurations (VH and HV) do not offer a clear and completly satisfying display. But this PR is a first attempt to display multi-substation graphs. It will be followed by another PR to represent multi-substation graphs according to a matrix design.

**Pull request merged**
